sudo: required

dist: trusty

language: python

python:
  - 3.6

branches:
  only:
    - master

addons:
    apt:
      update: true

env:
  global:
    - JOBS=1

cache:
  directories:
    - "node_modules"

before_install:
  - pip install -U pip
  - npm config set spin false

install:
  - pip install awscli

before_script:
  - npm i -g npm@latest
  - npm i -g create-react-app
  - npm i

script:
  - npm test
  - npm run build

deploy:
  on:
    branch: master
  provider: s3
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  bucket: $S3_BUCKET
  region: $S3_BUCKET_REGION
  skip_cleanup: true
  local_dir: build
  cache_control: "max-age=21600"

after_deploy:
  - aws configure set preview.cloudfront true
  - aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DISTRIBUTION_ID --paths "/*"

notifications:
  email:
    on_failure: change
    on_success: change